#!/bin/bash

# Колірні коди
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # Скидання форматування

# Розділення змінної $1 на дві частини
if [ -n "$1" ]; then
  IFS='/'
  read -r firstPart1 secondPart1 <<< "$1"
  IFS=' '
fi

# Виконання відповідних дій залежно від першої та другої частини
if [ "$firstPart1" = "make" ] && [ "$secondPart1" = "property" ]; then
  php console.php "$1" "$2" "$3"

elif [ "$1" = "-v" ] || [ "$1" = "--version" ]; then
  echo -e "\n\n${GREEN}APROG${NC} version ${YELLOW}1.1.0${NC} 2024.08.24 12:00:40\n"

elif [ "$1" = "build" ]; then
  docker-compose build

elif [ "$1" = "up" ]; then
  docker-compose up --no-recreate -d

elif [ "$1" = "down" ]; then
  docker-compose down

elif [ "$1" = "restart" ]; then
  docker-compose down && docker-compose up --no-recreate -d

elif [ -n "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo -e "\n\n${GREEN}APROG${NC} version ${YELLOW}1.3${NC} 2024.08.24 12:00:40\n"
  echo -e "${YELLOW}Використання:${NC}"
  echo -e "  aprog [команда] [аргумент] [опція]"
  echo -e "  aprog [опція]\n"
  echo -e "${YELLOW}Опції:${NC}"
  echo -e "${GREEN}  -h, --help${NC}     Вивід інформації на екран"
  echo -e "${GREEN}  -v, --version${NC}  Вивід версії програми на екран"
  echo -e "${GREEN}  -p, --params${NC}   Додаткові параметри для команд\n"
  echo -e "${YELLOW}Команди:${NC}"
  echo -e "${GREEN}  make${NC}           Створити об'єкт, клас або модель"

fi
